<?php

declare(strict_types=1);

namespace Apermo\SiteBookkeeperReporter;

/**
 * Manages the mu-plugin loader stub installation.
 *
 * The loader stub is a small file in the mu-plugins directory that
 * requires the main plugin file for early loading. It includes a
 * file_exists() guard so it's safe to commit to version control.
 */
class MuPluginInstaller {

	private const LOADER_FILENAME = 'site-bookkeeper-reporter-loader.php';

	/**
	 * Get the full path to the mu-plugin loader file.
	 *
	 * @return string
	 */
	public static function get_loader_path(): string {
		return \WPMU_PLUGIN_DIR . '/' . self::LOADER_FILENAME;
	}

	/**
	 * Generate the loader file content.
	 *
	 * @return string
	 */
	public static function get_loader_content(): string {
		$plugin_file = plugin_dir_path( Plugin::file() ) . 'plugin.php';

		return <<<PHP
		<?php
		// Auto-generated by Site Bookkeeper Reporter. Safe to commit to version control.

		if ( file_exists( '{$plugin_file}' ) ) {
			require_once '{$plugin_file}';
		}

		PHP;
	}

	/**
	 * Check if the loader file is installed.
	 *
	 * @return bool
	 */
	public static function is_installed(): bool {
		return \file_exists( self::get_loader_path() );
	}

	/**
	 * Install the loader file.
	 *
	 * @return bool True on success, false on failure.
	 */
	public static function install(): bool {
		$path      = self::get_loader_path();
		$directory = \dirname( $path );

		if ( ! \is_dir( $directory ) ) {
			if ( ! wp_mkdir_p( $directory ) ) {
				return false;
			}
		}

		$content = self::get_loader_content();

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Direct write for mu-plugin loader.
		$result = \file_put_contents( $path, $content );

		return $result !== false;
	}

	/**
	 * Remove the loader file.
	 *
	 * @return bool True on success, false on failure.
	 */
	public static function uninstall(): bool {
		$path = self::get_loader_path();

		if ( ! \file_exists( $path ) ) {
			return true;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- Direct filesystem op for mu-plugin loader.
		return \unlink( $path );
	}
}
