<?php

declare(strict_types=1);

namespace Apermo\SiteMonitorReporter\Tests\Unit;

use Apermo\SiteMonitorReporter\MuPluginInstaller;
use Brain\Monkey;
use Brain\Monkey\Functions;
use PHPUnit\Framework\TestCase;

/**
 * Tests for the MuPluginInstaller class.
 */
class MuPluginInstallerTest extends TestCase {

	/**
	 * Set up Brain Monkey.
	 *
	 * @return void
	 */
	protected function setUp(): void {
		parent::setUp();
		Monkey\setUp();
	}

	/**
	 * Tear down Brain Monkey.
	 *
	 * @return void
	 */
	protected function tearDown(): void {
		Monkey\tearDown();
		parent::tearDown();
	}

	/**
	 * Verify loader file path points to mu-plugins directory.
	 *
	 * @return void
	 */
	public function test_get_loader_path(): void {
		if ( ! \defined( 'WPMU_PLUGIN_DIR' ) ) {
			// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound -- WP constant.
			\define( 'WPMU_PLUGIN_DIR', '/tmp/wp-content/mu-plugins' );
		}

		$path = MuPluginInstaller::get_loader_path();

		$this->assertSame(
			'/tmp/wp-content/mu-plugins/site-monitor-reporter-loader.php',
			$path,
		);
	}

	/**
	 * Verify generated loader content includes safety checks.
	 *
	 * @return void
	 */
	public function test_get_loader_content_includes_file_exists_check(): void {
		Functions\when( 'plugin_dir_path' )->justReturn( '/tmp/wp-content/plugins/site-monitor-reporter/' );

		$content = MuPluginInstaller::get_loader_content();

		$this->assertStringContainsString( 'file_exists', $content );
	}

	/**
	 * Verify generated loader content includes auto-generated comment.
	 *
	 * @return void
	 */
	public function test_get_loader_content_includes_comment(): void {
		Functions\when( 'plugin_dir_path' )->justReturn( '/tmp/wp-content/plugins/site-monitor-reporter/' );

		$content = MuPluginInstaller::get_loader_content();

		$this->assertStringContainsString(
			'Auto-generated by Site Monitor Reporter',
			$content,
		);
	}

	/**
	 * Verify generated loader content includes require statement.
	 *
	 * @return void
	 */
	public function test_get_loader_content_includes_require(): void {
		Functions\when( 'plugin_dir_path' )->justReturn( '/tmp/wp-content/plugins/site-monitor-reporter/' );

		$content = MuPluginInstaller::get_loader_content();

		$this->assertStringContainsString( 'require_once', $content );
	}

	/**
	 * Verify is_installed returns true when loader file exists.
	 *
	 * @return void
	 */
	public function test_is_installed_returns_true_when_file_exists(): void {
		$temp_dir = \sys_get_temp_dir() . '/mu-plugins-test-' . \uniqid();
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- Test filesystem setup.
		\mkdir( $temp_dir, 0755, true );
		$loader_path = $temp_dir . '/site-monitor-reporter-loader.php';
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Test filesystem setup.
		\file_put_contents( $loader_path, '<?php // test' );

		// Since the constant is already defined, we test file existence directly.
		$this->assertFileExists( $loader_path );

		// Cleanup.
		// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- Test filesystem cleanup.
		\unlink( $loader_path );
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir -- Test filesystem cleanup.
		\rmdir( $temp_dir );
	}

	/**
	 * Verify loader content targets the plugin entry file.
	 *
	 * @return void
	 */
	public function test_get_loader_content_targets_plugin_file(): void {
		Functions\when( 'plugin_dir_path' )->justReturn( '/tmp/wp-content/plugins/site-monitor-reporter/' );

		$content = MuPluginInstaller::get_loader_content();

		$this->assertStringContainsString( 'plugin.php', $content );
	}

	/**
	 * Verify loader content is valid PHP.
	 *
	 * @return void
	 */
	public function test_get_loader_content_is_valid_php(): void {
		Functions\when( 'plugin_dir_path' )->justReturn( '/tmp/wp-content/plugins/site-monitor-reporter/' );

		$content = MuPluginInstaller::get_loader_content();

		$this->assertStringStartsWith( '<?php', $content );
	}
}
